### ISSUE TITLE
2.5.0 breaks "/// <reference ..."

### ISSUE THREAD

**Issue by nillis** [frankwallis/plugin-typescript#88] opened 2016-01-25 14:32 UTC
The 2.5.0 version of the plugin causes errors when you have /// <references in your code and try to create a self invoking bundle with jspm bundle-sfx. I will investigate and provide more details.

**Comment by nillis** [comment] 2016-01-25 15:22
I created a sample which reproduces this issue:
https://github.com/nillis/ignore-typings

**Comment by frankwallis** [comment] 2016-01-25 19:35
If I add a reference in index.ts:

```
/// <reference path="..\typings\main.d.ts" />
class Directive implements ng.IDirective {
    template = `HELLO WORLD`;
}
```
I get
```
	
Heracles:ignore-typings frank$ jspm bundle-sfx src/index lib/bundle.js
     Building the single-file sfx bundle for src/index...
TypeScript file:///Users/frank/work/ignore-typings/typings/main/ambient/angular/angular.d.ts:65:43
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/frank/work/ignore-typings/typings/main/ambient/angular/angular.d.ts:997:43
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/frank/work/ignore-typings/typings/main/ambient/angular/angular.d.ts:1207:19
TypeScript Cannot find name 'JQuery'. (TS2304)
/* etc */
```
This is because the declaration files are installed with [typings](https://github.com/typings/typings) and it is stripping out references from the installed declaration files, see this issue: https://github.com/typings/typings/issues/113. 
If I change the reference to put angular and jquery in the right order then the project builds ok:
```
/// <reference path="../typings/main/ambient/jquery/jquery.d.ts" />
/// <reference path="../typings/main/ambient/angular/angular.d.ts" />

class Directive implements ng.IDirective {
    template = `HELLO WORLD`;
}
```
```
Heracles:ignore-typings frank$ jspm bundle-sfx src/index lib/bundle.js
     Building the single-file sfx bundle for src/index...
ok   Built into lib/bundle.js with source maps, unminified.
```

This is an incompatibility between plugin-typescript and the typings project, which I need to solve, I would probably recommend using [tsd](https://github.com/DefinitelyTyped/tsd) for the time being.

**Comment by nillis** [comment] 2016-01-25 21:07
I didn't encounter the order problem in my real project as the order of references in the main.d.ts and browser.d.ts there was ok. I make sure they are in the right order, but thanks for point out!

I changed my sample to simulate the "real" issue I encountered.
When you get the latest version, you can determine the following behaviour:

1) Version 2.4.9
Run jspm bundle-sfx command => bundle sucessfully created

2) Update plugin version to 2.5.1 (or 2.5.0)
Run jspm bundle-sfx command => bundle fail

```
➜  ignore-typings git:(master) ✗ jspm bundle-sfx src/index lib/bundle.js
     Building the single-file sfx bundle for src/index...
ok   Built into lib/bundle.js with source maps, unminified.
➜  ignore-typings git:(master) jspm update

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up npm:typescript
     Updating registry cache...
     Looking up github:frankwallis/plugin-typescript
ok   Up to date - typescript as npm:typescript@^1.6.2 (1.7.5)
ok   Installed ts as github:frankwallis/plugin-typescript@2.5.1 (2.5.1)
     Clearing configuration for github:frankwallis/plugin-typescript@2.4.9
     Removing package files for github:frankwallis/plugin-typescript@2.4.9
ok   Install tree has no forks.

ok   Install complete.
➜  ignore-typings git:(master) ✗ jspm bundle-sfx src/index lib/bundle.js
     Building the single-file sfx bundle for src/index...
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:65:43
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:997:43
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1207:19
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1227:26
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1712:46
TypeScript Cannot find name 'JQueryStatic'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1717:18
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1723:40
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1729:19
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1736:49
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript file:///Users/nillis/Desktop/ignore-typings/typings/browser/ambient/angular/angular.d.ts:1737:54
TypeScript Cannot find name 'JQuery'. (TS2304)
TypeScript compilation failed [5 files, 1 failed, 0 unchecked] (TS9999)
TypeScript compilation failed [5 files, 1 failed, 0 unchecked] (TS9999)

err  Error: Typescript compilation failed
         at file:///Users/nillis/Desktop/ignore-typings/jspm_packages/github/frankwallis/plugin-typescript@2.5.1/plugin.js:55:31
```

**Comment by frankwallis** [comment] 2016-01-25 22:34
Thanks, that should be fixed in 2.5.2. It was again caused by typings stripping out the references, so the dependency tree was not correct. I have made a change to which I think will make typings and plugin-typescript play much more nicely with each other.

**Comment by nillis** [comment] 2016-01-26 07:28
Great! Thanks for the quick fix and follow up. I will this today. You also asked to test the hot reloading a few days ago. What should this feature do?

**Comment by nillis** [comment] 2016-01-26 08:52
I tested this and encountered another error by accident.
I used / as path separator in my project when I referenced typings. This caused the plugin-typescript@2.5.2 to fail when creating a bundle-sfx.
When using \ as path separator, then bundle-sfx runs ok.
You can simulate this behaviour with the latest version of https://github.com/nillis/ignore-typings

In index.ts
```
/// <reference path="..\typings\main.d.ts" /> => OK
```

```
/// <reference path="../typings/main.d.ts" /> => NOK
```

**Comment by nillis** [comment] 2016-01-26 09:04
I tried to debug the plugin using node-debug, but it didn't break in the plugin. Can you please share you local setup or how you debug such errors? This would help me contributing to this plugin instead of just reporting issues ;)

**Comment by frankwallis** [comment] 2016-01-26 11:49
If I really need to step through the code I use ```node-inspector``` and ```mocha --debug```. Normally though I just stick in some console logging to see what is going on.

I am a bit surprised that this doesn't work because most ```/// reference``` comments use forward slash, and I have not really seen any with backslashes before now. TypeScript provides a function ```ts.normalizePath``` which switches everything to forward slash so probably that needs to be called somewhere.

**Comment by frankwallis** [comment] 2016-01-26 19:21
I found it was the other way around for me - \ was breaking the build and / worked (which actually makes more sense to me). I have released a fix in 2.5.3 but you might want to check that has fixed what you were seeing, thanks.

re: the hot loading, all I wanted was just some general feedback on the updated version to see if anything had broken as I had to make some fairly major changes to accommodate the hot-reloading. What you have given me already has been great. The hot-reloading feature itself can be seen in the example react/angular projects, but I don't expect you to test it for me unless you are going to use it yourself...

**Comment by nillis** [comment] 2016-01-26 19:31
I will check the fix out tomorrow, but I'm sure it will work. Thx for the fast feedback and fixes!

I didn't know the systemjs hot loader plugin, but it's definitely worth checking out.

**Comment by nillis** [comment] 2016-01-29 08:39
I keep getting the error in my project. I'll check if it still occurs in the sample and if not, update it to the scenario of my project.

**Comment by frankwallis** [comment] 2016-02-06 13:42
I'm closing this, if it is still an issue please provide a repro, thanks.

**Closed by frankwallis** 2016-02-06 13:42 UTC

**Comment by nillis** [comment] 2016-02-10 08:33
Sorry for the late answer. I updated the sample (https://github.com/nillis/ignore-typings/tree/ba742c4f9f60b11fea4e7939f9d52eebd0ec3336) to reproduce the issue.
jspm 0.16.17
plugin-typescript 3.0.2

**Comment by nillis** [comment] 2016-02-10 08:42
I think there's a bigger issue, not only related to the typings, but I can't get any ts file through the bundle-sfx command. tsc is working fine.

**Comment by frankwallis** [comment] 2016-02-10 19:04
If you're using jspm@0.16.17 then I think you will need to use plugin-typescript@2.5.9. If you want to use plugin-typescript@3.0.2 then you need to upgrade to jspm 0.16.27.

**Comment by nillis** [comment] 2016-02-10 19:08
Excuse me it was a typo, it was 0.16.27

**Comment by nillis** [comment] 2016-02-11 08:31
Solved and discussed in https://github.com/nillis/ignore-typings/pull/1
