### ISSUE TITLE
Source Maps are off

### ISSUE THREAD

**Issue by Vaccano** [frankwallis/plugin-typescript#110] opened 2016-03-15 16:23 UTC
We recently upgraded to 4.0.2 (from 2.6.0) and the source maps are off now.

If I put a breakpoint (using Chrome Debugger) in a line of code in the `!transpiled` code, the view moves to the Typescript file and the break point is put a very different line of code (sometimes a comment).

**Comment by frankwallis** [comment] 2016-03-15 22:59
Can you tell me a bit more about your setup - what version of jspm are you using and are you piping the typescript output into babel?

**Comment by Vaccano** [comment] 2016-03-15 23:13
I am using JSPM 0.16.31

I am not piping into Babel (at least I am not trying to).

Here is what my config.js looks like:

    System.config({
      baseURL: ".",
      defaultJSExtensions: true,
      transpiler: "ts",
      typescriptOptions: {
        "tsconfig": true
      },
      paths: {
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*"
      },

      packages: {
        "src": {
          "main": "app",
          "defaultExtension": "ts",
          "meta": {
            "*.ts": {
              "loader": "ts"
            }
          },
          "*.js": {
            "loader": "ts"
          }
        }
      },

      map: {
        "app": "src/views/app/app",
        "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.1.0",
        "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.1",

.... Lots more maps that I don't think are relevant..

**Comment by Vaccano** [comment] 2016-03-15 23:21
In case it is relevant, here is my tsconfig file:

    {
	    "compilerOptions":{
            "target": "es5",
            "module": "system",
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true
	    },
      "exclude": [
        "node_modules",
        "jspm_packages"
      ]
    }

**Comment by mikeyoon** [comment] 2016-03-16 18:59
I'm getting a similar issue as well, but my sourcemaps tend to be off by one line, so when I'm debugging I have to put my breakpoints one line above where I expect.

**Comment by frankwallis** [comment] 2016-03-16 20:14
@mikeyoon what version of jspm are you using?

**Comment by mikeyoon** [comment] 2016-03-17 01:15
16.30

**Comment by frankwallis** [comment] 2016-03-17 07:41
I think this is most likely an issue in systemjs, I am able to recreate it but I can't fix it as I don't think the problem is caused by this plugin. There were some fixes for source maps in jspm 0.17.0-beta and they do seem to be working ok there.

**Comment by born2net** [comment] 2016-03-24 16:52
+1

**Comment by develar** [comment] 2016-03-25 11:10
I found the reason — it is a critical bug in the systemjs. See https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L21 This code is totally incorrect — systemjs must not add new line (to avoid one line offset issue) and doesn't add. But `;` is added to source mappings. And, so, we got one line offset issue.

So, fix is very simple — just remove this line. Workaround was added to WebStorm/IntelliJ IDEA (146 branch). I will try to prepare pull request to systemjs.

**Comment by frankwallis** [comment] 2016-03-25 12:48
@develar thanks for making that pull request, hopefully this issue will get resolved in the next release of systemjs.

**Comment by born2net** [comment] 2016-03-25 13:40
I just want to say tx to @develar, I was working with him to resolve this issue and he is an incredible developer at JetBrains making the product solid, tx again devlar!!!

**Comment by born2net** [comment] 2016-03-25 15:20
I confirmed the bug is now fixed with @develar change, after weeks of struggle I can finally debug properly...

**Comment by born2net** [comment] 2016-03-25 21:30
FYI workaround has been put into WebStorm until fix is in system.js
http://stackoverflow.com/questions/36228177/jspm-system-js-debugging-with-typescript/36228328#36228328

**Comment by frankwallis** [comment] 2016-03-30 18:00
This has been resolved in jspm@0.17.0-beta.12 / systemjs@0.19.25

**Closed by frankwallis** 2016-03-30 18:00 UTC
