### ISSUE TITLE
Undefined when importing a property from object

### ISSUE THREAD

**Issue by JulianIsrael** [frankwallis/plugin-typescript#188] opened 2017-01-31 22:17 UTC
Edit: this was a change from systemjs, so that is expected.
When I use import { render } from 'react-dom'
console.log(render) // undefined.
this is my config:
typescriptOptions: {
    "allowJs": true,
    "tsconfig": false,
    "typeCheck": false,
    "module": "system",
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "removeComments": true,
    "noEmitHelpers": false,
    "importHelpers": false,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true
  }

edit: I'm now having this issue with the bundle that I got after updating the plugin:
Cannot read property 'moduleObj' of undefined when importing a module using System. This works in development environment but not after running jspm bundle.

**Comment by outring** [comment] 2017-02-08 18:52
+1 here, the same config works with System 0.19 but doesn't with 0.20

**Comment by frankwallis** [comment] 2017-02-25 10:18
I believe this is a duplicate of https://github.com/frankwallis/plugin-typescript/issues/185 - with systemjs@0.20 you can no longer used named imports from commonjs modules.

**Closed by frankwallis** 2017-02-25 10:18 UTC
