### ISSUE TITLE
Typecheck does not work with typescript@next

### ISSUE THREAD

**Issue by frederikschubert** [frankwallis/plugin-typescript#100] opened 2016-02-02 10:26 UTC
Hi,
I am trying to use the new [module resolution](https://github.com/Microsoft/TypeScript/issues/5039) of typescript but the plugin cannot find the modules ~~and no decorator metadata is emitted for the modules~~ that I load from my `jspm_packages` directory.
I added the following overrides to my `package.json`:
```json
    "devDependencies": {
      "json": "github:systemjs/plugin-json@0.1.0",
      "ts": "github:frankwallis/plugin-typescript@2.5.7",
      "typescript": "npm:typescript@1.9.0-dev.20160128"
    },
    "overrides": {
      "github:frankwallis/plugin-typescript@2.5.7": {
        "dependencies": {
          "typescript": "npm:typescript@1.9.0-dev.20160128"
        }
      },
      "npm:typescript@1.9.0-dev.20160128": {
        "browser": {},
        "map": {
          "buffer": "@empty",
          "child_process": "@empty",
          "fs": "@empty",
          "os": "@empty",
          "path": "@empty",
          "process": "@empty",
          "readline": "@empty"
        }
      }
    }
``` 

My typescriptOptions in my `config.js` looks like the following:
```json
transpiler: false,
  typescriptOptions: {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "module": "system",
    "noImplicitAny": false,
    "typeCheck": true,
    "tsconfig": true
  }
```
And one example path mapping from my `tsconfig.json`:
```json
    "baseUrl": "./jspm_packages",
    "paths": {
      "angular2/*": [
        "npm/angular2@2.0.0-beta.2/*"
      ],
    }
```

**Comment by frankwallis** [comment] 2016-02-02 11:28
I don't understand what the issue is here, can you tell me (a) what is happening, (b) what you expect to be happening, thanks.

**Comment by frederikschubert** [comment] 2016-02-02 11:43
My editor (VSCode) and the typescript compiler in version 1.9.0-dev.20160128 can process the `compilerOptions.paths` and `compilerOptions.baseUrl` configuration correctly but it seems that the ts plugin does not use them.
I looks as the version override for the typescript compiler for the ts-plugin is not being used, because the plugin cannot find the modules that are mapped in the `tsconfig.json`.

**Comment by frankwallis** [comment] 2016-02-02 13:40
The plugin does not use the paths in tsconfig.json, it uses the systemjs map configuration. The paths configuration in tsconfig.json should be derived from the systemjs configuration, but the systemjs configuration should be the source of truth IMHO.

Is the issue here specifically to do with resolving the 'typings' files in angular2 beta?

**Comment by frederikschubert** [comment] 2016-02-02 13:56
I think I may have not expressed my problem properly.
The application runs without problems using your plugin and angular2. My only problem is the type checking. Because typescripts `"moduleResolution": "node"` only looks for typings in the `node_modules` directory, it could not find the typings of modules (that ship their typings with their npm distribution) in the `jspm_packages` directory.
Since last week there is this addition to typescript's module resolution that is based on a baseUrl and path mappings. So to align the module resolution of systemjs and the typescript compiler, one can now specify these mappings in the `tsconfig.json`.

I wrote a small tool that reads the mappings in `config.js` and adds the needed path mappings to the `tsconfig.json`.
So the single source of truth is still the systemjs configuration, but now typescript can use that and we have finally intellisense with modules that were installed via jspm.

I hope this explains my issue. Thank you for responding so fast!

**Comment by frankwallis** [comment] 2016-02-03 21:37
Thanks, I still think the problem here is to do with the angular2 typings, unfortunately due to restrictions of type-checking in the browser this is still an issue for plugin-typescript. See https://github.com/frankwallis/plugin-typescript/issues/102 for a full explanation. I realise this is an important issue and I'm hoping it can be resolved asap.

**Comment by frankwallis** [comment] 2016-02-27 15:50
I believe this has been resolved by https://github.com/frankwallis/plugin-typescript/issues/102 and the angular2 project is now type-checking and has paths configuration which can be used in the IDE.

If you think there is still an issue here then I will reopen, thanks.

**Closed by frankwallis** 2016-02-27 15:50 UTC

**Comment by frederikschubert** [comment] 2016-02-27 16:11
Looks good! Thank you!
